# A purrfect theme.
theme = "catppuccin_frappe"

[editor]
# I really don't know how can anyone live w/o relative line numbers.
line-number = "relative"
# Different colors for different modes in the bottom info line.
color-modes = true
# Keeping up w/ good practices.
mouse = false
# Use my Zsh shell.
shell = ["zsh", "-ic"]
# Instant completions.
completion-timeout = 5
# Enable visual columns.
rulers = [80, 100, 120]
# Enable indent guide.
indent-guides = { render = true }

[editor.lsp]
# Show progress messages from the running langugage servers.
display-messages = true
# Display inlay hints by default if the langugage server supports it.
display-inlay-hints = true

[editor.cursor-shape]
# Different cursor shapes for different modes.
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
# Enable the file picker to detect hidden files.
hidden = false

[keys.normal]
# Deselect on <ESC>.
esc = ["collapse_selection", "keep_primary_selection"]

# "Comma" minor mode -> used as a Vim-inspired "leader" key i.e. for
# user-defined custom mappings.
[keys.normal.","]
# Open a new temporary buffer with `lazydocker` started.
d = [":new", ":insert-output lazydocker", ":redraw", "jump_backward"]
# Open a new temporary buffer with `lf` started.
e = [":new", ":insert-output lf", ":redraw", "jump_backward"]
# Open a new temporary buffer with `lazygit` started.
g = [
  ":new",
  ":insert-output lazygit",
  ":redraw",
  "jump_backward",
  ":reload-all",
]

# "Slime" minor mode -> Slime-like utility mappings to send text across tmux
# panes.
[keys.normal."\\".s]
# Joins selected lines by replacing newlines with spaces and sends selection to 
# the second tmux pane in the current window i.e. to the pane on the right.
# NOTE: Works best with only 2 panes per window:
#         - the left pane for helix;
#         - the right pane for shell/REPL;
s = [
  ":pipe-to > /tmp/helix-slime-latest",
  ":sh tr '\n' ' ' < /tmp/helix-slime-latest | tee /tmp/helix-slime-latest",
  ":sh cat /tmp/helix-slime-latest | xargs -0 -I % tmux send-keys -t 2 %",
]
# Just like the mapping above except this one doesn't join the lines.
S = [
  ":pipe-to > /tmp/helix-slime-latest",
  ":sh cat /tmp/helix-slime-latest | xargs -0 -I % tmux send-keys -t 2 %",
]
# r and R mappings are like s and S respectively. However, 'r' and 'R' also
# send a Return/Enter key after the piped text. Useful for sending to shells. 
r = [
  ":pipe-to > /tmp/helix-slime-latest",
  ":sh tr '\n' ' ' < /tmp/helix-slime-latest | tee /tmp/helix-slime-latest",
  ":sh cat /tmp/helix-slime-latest | xargs -0 -I % tmux send-keys -t 2 % Enter",
]
R = [
  ":pipe-to > /tmp/helix-slime-latest",
  ":sh cat /tmp/helix-slime-latest | xargs -0 -I % tmux send-keys -t 2 % Enter",
]
# Re-send the latest text.
l = [
  ":sh cat /tmp/helix-slime-latest | xargs -0 -I % tmux send-keys -t 2 % Enter",
]
