# A purrfect theme.
theme = "catppuccin_frappe"

[editor]
# I really don't know how can anyone live w/o relative line numbers.
line-number = "relative"
# Keeping up w/ good practices.
mouse = false
# Use my Zsh shell.
shell = ["zsh", "-ic"]
# Instant completions.
completion-timeout = 5
# Enable visual columns.
rulers = [80, 100, 120]

[editor.cursor-shape]
# Different cursor shapes for different modes.
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
# Enable the file picker to detect hidden files.
hidden = false

[keys.normal]
# Deselect on <ESC>.
esc = ["collapse_selection", "keep_primary_selection"]

# Create an "Action" minor mode.
[keys.normal."\\"]
d = [":new", ":insert-output lazydocker", ":redraw", "jump_backward"]
e = [":new", ":insert-output lf", ":redraw", "jump_backward"]
g = [
  ":new",
  ":insert-output lazygit",
  ":redraw",
  "jump_backward",
  ":reload-all",
]
