## Language servers configurations.

[language-server.rust-analyzer.config.check]
command = "clippy"

## Custom language servers.

## Language server for buffer text completions and snippets.
#   - Set max completion results len to 20.
#   - Completions will return before snippets by default.
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20    # Set max completion results len for each group: words, snippets, unicode-input.
snippets_first = true        # Completions will return before snippets by default.
feature_words = true         # Enable completion by word.
feature_snippets = true      # Enable snippets.
feature_unicode_input = true # Enable "unicode input".
feature_paths = true         # Enable path completion.

# Emmet integration for helix.
[language-server.emmet-ls]
command = "emmet-language-server"
args = ["--stdio"]

# Vimscript support.
[language-server.vim-ls]
command = "vim-language-server"
args = ["--stdio"]

# Protobuf support.
[language-server.protobuf-ls]
command = "protobuf-language-server"
args = ["-stdio"]

## Language-specific configurations.

# Web-specific programming languages.
[[language]]
name = "html"
language-servers = [
  "scls",
  "tailwindcss-ls",
  "emmet-ls",
  "vscode-html-language-server",
]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "css"
language-servers = ["scls", "tailwindcss-ls", "vscode-css-language-server"]
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "scss"
language-servers = ["scls", "tailwindcss-ls", "vscode-css-language-server"]
formatter = { command = "prettier", args = ["--parser", "scss"] }

[[language]]
name = "javascript"
language-servers = ["scls", "typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  "scls",
  "tailwindcss-ls",
  "emmet-ls",
  "vscode-html-language-server",
  "typescript-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["scls", "typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "scls",
  "tailwindcss-ls",
  "emmet-ls",
  "vscode-html-language-server",
  "typescript-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

# Programming languages.
[[language]]
name = "rust"
language-servers = ["scls", "rust-analyzer"]
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "go"
language-servers = ["scls", "gopls", "golangci-lint-lsp"]
formatter = { command = "gofumpt" }

[[language]]
name = "templ"
language-servers = [
  "scls",
  "tailwindcss-ls",
  "emmet-ls",
  "vscode-html-language-server",
  "templ",
]
formatter = { command = "templ", args = ["fmt", "-stdout"] }
auto-format = true

[[language]]
name = "gleam"
language-servers = ["scls", "gleam"]

[[language]]
name = "java"
formatter = { command = "google-java-format", args = ["-"] }
language-servers = ["scls", "jdtls"]
auto-format = true

# Scripting languages.
[[language]]
name = "bash"
language-servers = ["scls", "bash-language-server"]
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "vimscript"
scope = "source.vim"
file-types = ["vim", "ideavimrc"]
roots = [".git"]
indent = { tab-width = 4, unit = " " }
auto-format = false
language-servers = ["scls", "vim-ls"]

# Data-based formats.
[[language]]
name = "toml"
language-servers = ["scls", "taplo"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "json"
language-servers = ["scls", "vscode-json-language-server"]
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "yaml"
language-servers = ["scls", "yaml-language-server", "ansible-language-server"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true

[[language]]
name = "protobuf"
language-servers = ["scls", "protobuf-ls", "pbkit"]
auto-format = true

# Markdown.
[[language]]
name = "markdown"
language-servers = ["scls", "marksman", "markdown-oxide"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
