[[language]]
name = "toml"
language-servers = ["taplo", "simple-completion"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["markdown", "simple-completion"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true
language-servers = ["yaml-language-server", "simple-completion"]

# Custom language servers.

# Language server for buffer text completions and snippets.
# - Set max completion results len to 20.
# - Completions will return before snippets by default.
[language-server.simple-completion]
command = "simple-completion-language-server"

[language-server.simple-completion.config]
max_completion_items = 20    # Set max completion results len for each group: words, snippets, unicode-input.
snippets_first = true        # Completions will return before snippets by default.
feature_words = true         # Enable completion by word.
feature_snippets = true      # Enable snippets.
feature_unicode_input = true # Enable "unicode input".
feature_paths = true         # Enable path completion.

# Snippets configuration.

[[sources]] # List of sources to load.
name = "friendly-snippets"                                  # Optional name shown on snippet description.
git = "https://github.com/rafamadriz/friendly-snippets.git" # Git repo with snippets collections.
