[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--parser", "scss"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "emmet-ls", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "emmet-ls", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "go"
formatter = { command = "gofumpt" }
auto-format = true

[[language]]
name = "templ"
language-servers = [
  "templ",
  "vscode-html-language-server",
  "emmet-ls",
  "tailwindcss-ls",
]
formatter = { command = "templ", args = ["fmt", "-stdout"] }
auto-format = true

[[language]]
name = "java"
formatter = { command = "google-java-format", args = ["-"] }
auto-format = true

[[language]]
name = "scala"
formatter = { command = "scalafmt", args = ["--stdin", "--stdout"] }
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "vimscript"
scope = "source.vim"
file-types = ["vim", "ideavimrc"]
roots = [".git"]
indent = { tab-width = 4, unit = " " }
auto-format = false
language-servers = ["vim-language-server", "simple-completion"]

[[language]]
name = "toml"
language-servers = ["taplo", "simple-completion"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "protobuf"
language-servers = ["protobuf-language-server"]

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "simple-completion"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

# Existing language server extra configuration.

[language-server.rust-analyzer.config.check]
command = "clippy"

# Custom language servers.

# Language server for buffer text completions and snippets.
# - Set max completion results len to 20.
# - Completions will return before snippets by default.
[language-server.simple-completion]
command = "simple-completion-language-server"

[language-server.simple-completion.config]
max_completion_items = 20    # Set max completion results len for each group: words, snippets, unicode-input.
snippets_first = true        # Completions will return before snippets by default.
feature_words = true         # Enable completion by word.
feature_snippets = true      # Enable snippets.
feature_unicode_input = true # Enable "unicode input".
feature_paths = true         # Enable path completion.

[language-server.emmet-ls]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.vim-language-server]
command = "vim-language-server"
args = ["--stdio"]

[language-server.protobuf-language-server]
command = "protobuf-language-server"
args = ["-stdio"]

# Snippets configuration.

[[sources]] # List of sources to load.
name = "friendly-snippets"                                  # Optional name shown on snippet description.
git = "https://github.com/rafamadriz/friendly-snippets.git" # Git repo with snippets collections.
